# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/issues/**

linter:
  rules:
    - overridden_fields: false
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures

dart_code_metrics:
  exclude:
    metrics:
      - test/**
      - example/**
    rules:
      - test/**
      - example/**
  extends:
    - package:dart_code_metrics_presets/dart_all.yaml
  rules:
    - avoid-dynamic : false
    - avoid-non-null-assertion : false
    - newline-before-return : false
    - avoid-late-keyword : false