# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/issues_done/**

linter:
  rules:
    - overridden_fields: false
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
